name: Test Dev Proxy Actions with defaults

on:
  workflow_dispatch:

jobs:
  test-dev-proxy-actions-defaults:
    name: Test Dev Proxy Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Intall Dev Proxy
        id: install-latest
        uses: ./install

      - name: Start Dev Proxy
        id: start-devproxy
        uses: ./start          

      - name: Start recording
        id: start-recording
        uses: ./record-start

      - name: Send request
        id: send-request
        run: |
          curl -ikx http://127.0.0.1:8000 https://jsonplaceholder.typicode.com/posts

      - name: Stop recording
        id: stop-recording
        uses: ./record-stop

      - name: Show logs
        run: |
          echo "Dev Proxy logs:"
          cat devproxy.log
